project:
  name: quickstart-starwind-vsan
  regions:
  - eu-west-1
  package_lambda: false
  s3_regional_buckets: true
  parameters:
    AvailabilityZones: $[taskcat_genaz_3]
    KeyPairName: $[taskcat_getkeypair]
    WorkloadInstanceType: m5.xlarge
    AdminPassword: $[taskcat_genpass_8S]
    RDGWCIDR: 10.0.0.0/32
    QSS3KeyPrefix: "quickstart-starwind-vsan/"
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  new-vpc-2019:
    template: ./templates/swvsan-entrypoint-new-vpc.template.yaml
    parameters:
      SWVSANAMIOS: WindowsServer2019
  new-vpc-2016:
    template: ./templates/swvsan-entrypoint-new-vpc.template.yaml
    parameters:
      SWVSANAMIOS: WindowsServer2016
