AWSTemplateFormatVersion: '2010-09-09'
Description:
  This template deploys an EC2 instnace using the StarWind VSAN
  Marketplace AMI in an existing VPC. It also creates a total of 3 Elastic Network
  Interfaces (ENIs) and attaches them to the instance.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VPCID
      - PrivateSubnet1ID
      - PrivateSubnet2ID
      - PrivateSubnet3ID
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - NodeOrWitness
      - SWVSANEC2InstanceName
      - WorkloadInstanceType
      - SWVSANStorageVolumeSize
      - KeyPairName
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      VPCID:
        default: VPC ID
      WorkloadInstanceType:
        default: Workload instance type
      SWVSANStorageVolumeSize:
        default: Secondary EBS volume size
      SWVSANEC2InstanceName:
        default: StarWind VSAN instance name
      NodeOrWitness:
        default: Storage Node or Witness
  AWSAMIRegionMap:
    Filters:
      VSANWIN2019:
        description: 'swvsanhourly19_(Marketplace)'
        owner-id: '679593333241'
      VSANWIN2016:
        description: 'swvsanhourly16_(Marketplace)'
        owner-id: '679593333241'
Parameters:
  KeyPairName:
    Description: Name of an existing EC2 key pair. The instance will launch with
      this key pair.
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet1ID:
    Description: (Ignored for Witness) ID of private subnet 1 in Availability Zone 1 used for iSCSI ENI (e.g.,
      subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: ID of private subnet 2 in Availability Zone 1 for management/witness ENI (e.g.,
      subnet-b1f432cd).
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet3ID:
    Description: (Ignored for Witness) ID of private subnet 3 in Availability Zone 1 for syncronization ENI (e.g.,
      subnet-b1f432cd).
    Type: AWS::EC2::Subnet::Id
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-examples/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  VPCID:
    Description: ID of your existing VPC for deployment.
    Type: AWS::EC2::VPC::Id
  WorkloadInstanceType:
    AllowedValues:
    - c5.12xlarge
    - c5.18xlarge
    - c5.24xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.metal
    - c5d.18xlarge
    - c5d.2xlarge
    - c5d.4xlarge
    - c5d.9xlarge
    - c5n.18xlarge
    - c5n.2xlarge
    - c5n.4xlarge
    - c5n.9xlarge
    - c5n.metal
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - f1.16xlarge
    - g2.2xlarge
    - g2.8xlarge
    - g3.16xlarge
    - g3.4xlarge
    - g3.8xlarge
    - g4dn.12xlarge
    - g4dn.16xlarge
    - g4dn.2xlarge
    - g4dn.4xlarge
    - g4dn.8xlarge
    - h1.16xlarge
    - h1.2xlarge
    - h1.4xlarge
    - h1.8xlarge
    - hs1.8xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - i3.16xlarge
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - i3.metal
    - i3en.12xlarge
    - i3en.24xlarge
    - i3en.2xlarge
    - i3en.3xlarge
    - i3en.6xlarge
    - i3en.large
    - i3en.metal
    - i3en.xlarge
    - m5.12xlarge
    - m5.16xlarge
    - m5.24xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.8xlarge
    - m5.metal
    - m5a.12xlarge
    - m5a.16xlarge
    - m5a.24xlarge
    - m5a.2xlarge
    - m5a.4xlarge
    - m5a.8xlarge
    - m5ad.12xlarge
    - m5ad.24xlarge
    - m5ad.2xlarge
    - m5ad.4xlarge
    - m5d.12xlarge
    - m5d.16xlarge
    - m5d.24xlarge
    - m5d.2xlarge
    - m5d.4xlarge
    - m5d.8xlarge
    - m5d.metal
    - m5dn.12xlarge
    - m5dn.16xlarge
    - m5dn.24xlarge
    - m5dn.2xlarge
    - m5dn.4xlarge
    - m5dn.8xlarge
    - m5n.12xlarge
    - m5n.16xlarge
    - m5n.24xlarge
    - m5n.2xlarge
    - m5n.4xlarge
    - m5n.8xlarge
    - p2.16xlarge
    - p2.8xlarge
    - p3.16xlarge
    - p3.2xlarge
    - p3.8xlarge
    - p3dn.24xlarge
    - r5.12xlarge
    - r5.16xlarge
    - r5.24xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.8xlarge
    - r5.metal
    - r5a.12xlarge
    - r5a.16xlarge
    - r5a.24xlarge
    - r5a.2xlarge
    - r5a.4xlarge
    - r5a.8xlarge
    - r5ad.12xlarge
    - r5ad.24xlarge
    - r5ad.2xlarge
    - r5ad.4xlarge
    - r5d.12xlarge
    - r5d.16xlarge
    - r5d.24xlarge
    - r5d.2xlarge
    - r5d.4xlarge
    - r5d.8xlarge
    - r5d.metal
    - r5dn.12xlarge
    - r5dn.16xlarge
    - r5dn.24xlarge
    - r5dn.2xlarge
    - r5dn.4xlarge
    - r5dn.8xlarge
    - r5n.12xlarge
    - r5n.16xlarge
    - r5n.24xlarge
    - r5n.2xlarge
    - r5n.4xlarge
    - r5n.8xlarge
    - t3.2xlarge
    - t3a.2xlarge
    - x1.16xlarge
    - x1.32xlarge
    - x1e.16xlarge
    - x1e.2xlarge
    - x1e.32xlarge
    - x1e.4xlarge
    - x1e.8xlarge
    - z1d.12xlarge
    - z1d.2xlarge
    - z1d.3xlarge
    - z1d.6xlarge
    - z1d.metal
    ConstraintDescription: Must contain valid instance type.
    Default: m5.2xlarge
    Description: Type of EC2 instance for the workload instances.
    Type: String
  SWVSANStorageVolumeSize:
    Type: Number
    Default: 100
    ConstraintDescription: Must be between 1 GB and 16,000 GB (16 TB).
    MinValue: 1
    MaxValue: 16000
    Description: Size of StarWind VSAN virtualized storage in GBs.
  SWVSANEC2InstanceName:
    Type: String
    Default: StarWind Node X
  NodeOrWitness:
    Type: String
    Description: Type of the StarWind instance to be created.
    Default: Storage Node
    AllowedValues:
      - Storage Node
      - Witness
Rules:
  KeyPairsNotEmpty:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::EachMemberEquals:
          - Fn::RefAll: AWS::EC2::KeyPair::KeyName
          - ''
      AssertDescription: All key pair parameters must not be empty.
  SubnetsInVPC:
    Assertions:
    - Assert:
        Fn::EachMemberIn:
        - Fn::ValueOfAll:
          - AWS::EC2::Subnet::Id
          - VpcId
        - Fn::RefAll: AWS::EC2::VPC::Id
      AssertDescription: All subnets must be in the VPC.
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      VSANWIN2019: ami-0201dda502a86878a
      VSANWIN2016: ami-098b1f8c9a38223e2
    ap-northeast-2:
      VSANWIN2019: ami-02048526fb424985f
      VSANWIN2016: ami-0cf63dc40f791c584
    ap-south-1:
      VSANWIN2019: ami-0785c7f0867fdb89b
      VSANWIN2016: ami-0e6d64b76bb6e8942
    ap-southeast-1:
      VSANWIN2019: ami-08b820b2db28bd152
      VSANWIN2016: ami-0165b63db7cf72a58
    ap-southeast-2:
      VSANWIN2019: ami-0d6029ac0b5c859c9
      VSANWIN2016: ami-0ee9fb19795d9f75d
    ca-central-1:
      VSANWIN2019: ami-0fbc5c52fb9e68f51
      VSANWIN2016: ami-050d944a84d74ca19
    eu-central-1:
      VSANWIN2019: ami-07a8af581e68fffa6
      VSANWIN2016: ami-0dc3d6f78505eb09f
    eu-west-1:
      VSANWIN2019: ami-02cc88ff9e5245160
      VSANWIN2016: ami-0dc12011a64bfa637
    eu-west-2:
      VSANWIN2019: ami-09353f86f59556db7
      VSANWIN2016: ami-0ef8084cd5e1fbaae
    sa-east-1:
      VSANWIN2019: ami-03b398cd42ffc1103
      VSANWIN2016: ami-0c4dd65edd550991f
    us-east-1:
      VSANWIN2019: ami-0a9d7059c21ce60da
      VSANWIN2016: ami-0d30dc03c99322549
    us-east-2:
      VSANWIN2019: ami-09a7a26385b8153aa
      VSANWIN2016: ami-02c27155e49b40cf9
    us-west-1:
      VSANWIN2019: ami-0a9e24330eca7ea7f
      VSANWIN2016: ami-0ec023b0247c4fe58
    us-west-2:
      VSANWIN2019: ami-0aff346fe0fe591b2
      VSANWIN2016: ami-002085dff485ed331
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  IsStorageNode: !Equals [!Ref NodeOrWitness, 'Storage Node']
Resources:
  SWVSANEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSAMIRegionMap, !Ref 'AWS::Region', VSANWIN2019]
      InstanceType: !Ref WorkloadInstanceType
      KeyName: !Ref KeyPairName
      BlockDeviceMappings:
      - !If
          - IsStorageNode
          -
            DeviceName: /dev/sdf
            Ebs:
              VolumeSize: !Ref SWVSANStorageVolumeSize
          - !Ref 'AWS::NoValue'
      Tags:
        - Key: Name
          Value: !Ref SWVSANEC2InstanceName
      NetworkInterfaces:
        - Description: Management/Witness ENI
          DeviceIndex: '0'
          # GroupSet:
          #   - String
          # PrivateIpAddress: PrivateIpAddress
          SubnetId: !Ref PrivateSubnet2ID
        - !If
            - IsStorageNode
            -
              Description: iSCSI ENI
              DeviceIndex: '1'
              # GroupSet:
              #   - String
              # PrivateIpAddress: PrivateIpAddress
              SubnetId: !Ref PrivateSubnet1ID
            - !Ref 'AWS::NoValue'
        - !If
            - IsStorageNode
            -
              Description: Syncronization ENI
              DeviceIndex: '2'
              # GroupSet:
              #   - String
              # PrivateIpAddress: PrivateIpAddress
              SubnetId: !Ref PrivateSubnet3ID
            - !Ref 'AWS::NoValue'
